### PR TITLE
Add support for more snippet languages

### PR DESCRIPTION
**Pull request by lorensr**

### CODE REVIEW

**Comment by abernix** [comment]
Should we rebase this?

**Comment by abernix** [comment]
@lorensr I'm happy to rebase this PR myself, if you'd like.  Though (as this PR was opened before GitHub turned it on by default for new PRs) I'd need you to check the "Allow edits from maintainers" checkbox, which should be over there ➡️➡️➡️ somewhere.

(This thing:
)


😄

**Comment by lorensr** [comment]
Oh, thanks! Sorry, I saw your comment last week, but had no idea it was my PR 😆 Totally forgot I did this

**Comment by abernix** [comment]
Thanks to toggling that for me, @lorensr!

Upon trying to rebase this, it has come to my attention that we've diverged from this method of defining out own syntax highlighting and Hexo now supports it natively.

I've added a syntax highlighting example to the example docs repository via https://github.com/meteor/theme-example/commit/06a4b7a70bc469dc26fe64384c1dcc7163954098, and it looks like the syntax highlighting options you added should work out of the box now, as long as they are one of [the classes supported by Highlight.js](highlightjs.readthedocs.io/en/latest/css-classes-reference.html).  Unfortunately, it looks like GraphQL still isn't quite supported, but should hopefully be [supported soon](https://github.com/isagalaev/highlight.js/issues/1471).

The Apollo theme example, demonstrating the syntax highlighting working can be seen [on this page](https://theme-example.netlify.com/apollo-hexo-config/syntax-highlighting.html)!

I'll close this, but happy to reopen if you disagree.  Thanks for looking at this originally, even if it may have fell into the abyss.  (Sorry about that! We'll try not to let that happen again!)

**Pull request closed without merging**
