### PR TITLE
Move analytics keys to config

### PR DESCRIPTION
**Pull request by stubailo**
Still to do:

- [ ] Swiftype
- [ ] Nectar ninja

(I don't use those in Apollo yet, so we should test them with the guide)

### CODE REVIEW

**Comment by stubailo** [comment]
Wait, now I'm confused who our search provider is. Did we just have a useless code blob from swiftype? or are we using docsearch? No clue...

**Comment by tmeasday** [comment]
Docsearch. Here's what I was talking about: https://github.com/meteor/guide/issues/237

**Comment by tmeasday** [comment]
I'm not sure we use swiftype or nectar ninja (like NN seems to be setup but I don't know what it does)

**Comment by stubailo** [comment]
@tmeasday NN lets @danahmadi post announcements like Meteor night via twitter. We def want it.

**Pull request merged**
