### PR TITLE
Apollo branch

### PR DESCRIPTION
**Pull request by stubailo**

### CODE REVIEW

**Comment by stubailo** [comment]
(Opened this for the record, I think we need to merge in some of the general improvements or else the thing will keep diverging)

**Comment by abernix** [comment]
I've become acutely aware of this twice now this month.  I actually think the branches are pretty close and that Meteor _and_ Apollo can (and were supposed to, I believe!) share the same theme.  I think I can make this happen.

That said, I kinda wish there was a `greenkeeper` for `git submodule`.  If I get this to work on a converged theme, it might be worth considering using `git subtree` in lieu of `git submodule` so all the repos always deploy the latest versions of this theme.  Maybe setup some sort of global deploy hook that makes all of our repos redeploy this theme automatically?

**Comment by abernix** [comment]
Superseded by #51, finally. 🎉 🌮

**Comment by abernix** [comment]
Note to anyone who might be tempted to hit the "Delete branch" button on the `apollo` branch: **Don't.**

If a remote branch isn't maintained, our Git submodule-yielding repositories won't be able to find the commit as it will be detached from any head on Github.  Once all known themes are on the npm flavor of the theme, we can delete `apollo` to avoid confusion.

**Comment by abernix** [comment]
Update: I've set the branch to protected on GitHub so it _cannot_ be deleted.

**Pull request closed without merging**
